### ISSUE TITLE
make latest url point to latest release

### ISSUE THREAD

**Issue by richtoy** [IndraGunawan/cloudflared-armv6#1]
I am trying to automate updating to the latest version without knowing the version.
With the cloudflare github site I can use
https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64

but none of these resolve on your github repository
https://github.com/IndraGunawan/cloudflared-armv6/releases/latest/cloudflared
https://github.com/IndraGunawan/cloudflared-armv6/releases/download/latest/cloudflared

only a url with the version embedded works
https://github.com/IndraGunawan/cloudflared-armv6/releases/download/2024.10.1-22/cloudflared

**Comment by IndraGunawan** [comment]
The url structure that you share between cloudflare repo and this repo are different 

Try this https://github.com/IndraGunawan/cloudflared-armv6/releases/latest/download/cloudflared

**Comment by IndraGunawan** [comment]
The download url structure that you share between cloudflare repo and this repo is different

Try this https://github.com/IndraGunawan/cloudflared-armv6/releases/latest/download/cloudflared

**Comment by richtoy** [comment]
Thanks
